### ISSUE TITLE
Do you have time to take a look at my code?  TY

### ISSUE THREAD

**Issue by delebash** [colkassad/terrain-rgb-converter#6]
I am trying to create an all client side version using your functions.  I think I am close but I am not quite getting it right when I create a new PNG.  I can write the file but it is no good.  Maybe I am buffering it wrong or need to turn it to a blob.  I have been working on this unsuccessfully for awhile.  Any help would be appreciated.  If you can help let me know and I will send you the code. I have been learning about Png rgb extracting heights and all that stuff., it has been fun but I still don't understand a lot of things. TY again for this awesome conversion utility. Cheers!

**Comment by colkassad** [comment]
Sorry for responding so late, this slipped under the cracks. Feel free to send me the code. My username at gmail dot com. I can't promise to be able to help you but I can try.

**Comment by delebash** [comment]
No worries, I figured it out.  Thanks for your code it helped me out a lot!
